
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wncyfbkhgwcpbpbtbwaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduY3lmYmtoZ3djcGJwYnRid2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDQxMjEsImV4cCI6MjA2NjQ4MDEyMX0.QyYLjCWR6Y5xXVP9i7O1wOFNLL2gYYhB6vWr-pFh4Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
