// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpsegomkhytxhsatzgyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwc2Vnb21raHl0eGhzYXR6Z3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjcyMDcsImV4cCI6MjA2NTUwMzIwN30.It9u5-jVLm9k6MflrISSFWUBv1R2hXFbqiYOgsNAs0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);